version: "2"
services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:latest
    #entrypoint: docker-entrypoint.sh --sql-mode='STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    ports:
      - 1433:1433
    networks:
      - sql_server
    environment:
      - MSSQL_SA_PASSWORD=QWer1234*()
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
      - MSSQL_TCP_PORT=1433
    container_name: sql_server
networks:
  sql_server:
    external:
      name: sql_server_network